### ISSUE TITLE
Some segments end up having the entire list inside them

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-mailchimp#11]
I.E. https://us6.admin.mailchimp.com/lists/members/?id=216669#p:1-s:10-so:false

**Comment by michaloo** [comment]
Is there any pattern in circumstances of that problem?
Does it happen often?
Does affected accounts or segments have something in common?

**Comment by unity** [comment]
Was due to bad segmentation rules in dashboard. Closing #11
