### ISSUE TITLE
Upstream User sync

### ISSUE THREAD

**Issue by unity** [hull-ships/hull-mailchimp#12]
# We want users in Mailchimp to be captured by Hull
- [x] New users should be captured when they're added
- [x] Customer properties in Mailchimp should be captured
- [x] Subscription status should also be captured as a boolean property
- [x] Existing users should be imported when authenticating the app
- [x] There should be a button in the dashboard to force a re-capture of existing users. Use case: Customer imported new users from a CSV in Mailchimp.

**Comment by sbellity** [comment]
We capture all merge fields except custom groupings for now

**Comment by sbellity** [comment]
The sync step displayed on the Ship's dashboard starts a 2-way sync process. 
- All users on the list are imported to hull 
- All hull users are imported in the list

New members list subscriptions and updates are synced back to hull

**Comment by unity** [comment]
When you say all hull users are sent to Mailchimp. Do you mean all users or all who belong in the segments defined in settings ?

**Comment by michaloo** [comment]
We need to verify if all features here work correctly.

@unity - regarding your last question - only those who belong to the selected segments.
