### ISSUE TITLE
Extract multipart batch from mailchimp fails

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-mailchimp#20]
`MailchimpClient.handleResponse` fails if the tar has multiple entries. It just processes the first entry and then hangs which causes the calling job to timeout.

**Comment by sbellity** [comment]
https://github.com/thorning/node-mailchimp/blob/master/index.js#L172 

For an implementation that should work.

**Comment by michaloo** [comment]
Hm, the version on develop branch should work:

```js
extract.on("entry", (header, stream, callback) => {
      if (header.name.match(/\.json/)) {
        stream.pipe(decoder, { end: false });
      }

      stream.on("end", () => callback()); // ready for next entry
      stream.on("error", () => callback()); // ready for next entry

      stream.resume();
    });

    extract.on("finish", () => decoder.end());
    extract.on("error", () => decoder.end());

    request(response_body_url)
      .pipe(zlib.createGunzip())
      .pipe(extract);

    return decoder
      .pipe(es.map(function write(data, callback) {
        return data.map(r => {
          return callback(null, r);
        });
      }));
```

The reason why I didn't copied solution from that mailchimp api lib is because they concatenate whole batch response to flat string in memory at once here(https://github.com/thorning/node-mailchimp/blob/master/index.js#L213).
What I wanted to achieve is to parse it using streams only

**Comment by sbellity** [comment]
Running the develop branch locally

**Comment by michaloo** [comment]
Thanks, I'm already investigating it, while working on mailchimp-ship refactor.

**Comment by michaloo** [comment]
I have found out the source of the problem:
```
return decoder
      .pipe(es.map(function write(data, callback) {
        return data.map(r => {
          return callback(null, r);
        });
      }));
```
when `data` is empty the callback is never called, so it happened at different parts of the mailchimp response.

**Comment by michaloo** [comment]
Fix prepared here:
https://github.com/hull-ships/hull-mailchimp/commit/6c4a153b5b4e19e3afb38c8fd1f911611aa13141
