### ISSUE TITLE
User not added to the list if does not match any segment

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-mailchimp#7]
- Create a user that matches no segment
- It will not be added as a subscriber to the mailchimp list

**Comment by unity** [comment]
How is this an issue ? It seems to me like expected behavior

**Comment by sbellity** [comment]
Example : 

- I am a shopify Shop and I install the Mailchimp ship. 
- I want all my users to end up in the list.
- I click sync and all my users are added to my list. 
- Then a new user signs up but matches none of my segments (or I have zero segments defined in my org).

The expected behaviour here is that the user should be added to my list, currently he is not.

**Comment by michaloo** [comment]
Just wanted to do a follow-up here. It is still considered a bug and needs a fix?

**Comment by unity** [comment]
- if segment filter is empty, then all users go to Mailchimp list
- if segment filter has value, then only users matching at least one of those are synced.
- In both cases, all segments for these synced users should be synchronized.
