### ISSUE TITLE
add support for namespaces in the kue adapter

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-mailchimp#9]
cf. https://github.com/hull-ships/hull-hubspot/blob/master/server/bootstrap.js

**Comment by michaloo** [comment]
Prepared in #10.

**Comment by michaloo** [comment]
Prefix support tested on staging and pushed to prod.
I've some issues with kue-dashboard tough, can see the jobs in the prefixed queue. I will figure it out.
